In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv('vanlifetrader_data.csv')

In [3]:
raw_data.head()

,Unnamed: 0,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,...,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat,Handicap / Wheelchair Conversion
0,0,2021 Ram Promaster City Weekender,39500.0,"107 Diversified Dr, Villa Ridge, Missouri 6308...",2021,Ram Promaster,38.0,2WD,Clean,Automatic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2019 4x4 2500 Mercedes Sprinter - Luxury Apart...,135000.0,"Queens, New York 11694, United States",2019,Mercedes Sprinter 2500 4x4,17000.0,4WD,Clean,Automatic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Outside Van Family Camper,115000.0,"Granville, Ohio, United States",2014,Mercedes Benz,61500.0,2WD,Clean,Automatic,...,True,True,True,True,True,NaN,NaN,NaN,NaN,NaN
3,3,Awesome Stealthy Adventure Van // PRICE REDUCE...,55000.0,"Murfreesboro, Tennessee, United States",2016,Ram Pro Master 2500 159 WB Diesel,39000.0,2WD,Lien,Automatic,...,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN
4,4,Beautiful 2021 Van just waiting for an artisti...,85999.0,"Nashville, Tennessee, United States",2021,2021 Dodge Ram Promaster,9065.0,2WD,Lien,Automatic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#raw_data.info()

In [5]:
raw_data.drop(columns=['Unnamed: 0','Handicap / Wheelchair Conversion'], inplace=True)

In [6]:
raw_data['Wheel Base Length'].value_counts()

 144.0     90
 159.0     87
 170.0     76
 148.0     33
 136.0     24
 118.0      7
 158.0      6
 140.0      4
 138.0      2
 146.0      2
 130.0      2
 171.0      1
 132.0      1
 145.0      1
 178.0      1
 121.0      1
 0.0        1
 17.0       1
 15.0       1
 156.0      1
 21.0       1
-144.0      1
 120.0      1
 126.0      1
 19.0       1
 59.0       1
 350.0      1
 18.0       1
 1559.0     1
Name: Wheel Base Length, dtype: int64

Data Cleaning/Prep Tasks:

- [x] calculate average MPG of gasoline vehicles, and assign this value to gasoline vehicles without an MPG value
- [x] calculate average MPG of diesel vehicles, and assign this value to diesel vehicles without an MPG value
- [x] combine indoor/outdoor showers
- [x] assign False values to all boolean columns that currently have no value in a given cell
- [x] find vans without mileage listed, determine their model year, and assign a mileage value based on the average mileage of other vans from that year

In [7]:
boolean_data = raw_data.drop(columns=['Vehicle','Price','Location','Manufacturing Year','Make & Model','Mileage','Drive',
                                      'Title Status','Transmission','Fuel','Fuel Efficiency (Highway)','Wheel Base Length',
                                      'Number of Seats with Seatbelts','Sleeping Capacity'])

In [8]:
boolean_data.fillna(False, inplace=True)

In [9]:
boolean_data.head()

,Air Bags,Air Conditioner,Audio System,Backup Camera,Bluetooth / Wifi,Cooler,Exterior Lights,Fresh Water Tank (Portable),Inverter,Refrigerator,...,Microwave,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat
0,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,True,True,True,True,True,False,True,True,True,True,...,True,True,True,True,True,True,False,False,False,False
3,True,False,True,True,True,False,False,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,True,True,True,True,False,True,True,False,True,True,...,False,False,False,False,False,False,False,False,False,False

In [10]:
boolean_data['Shower'] = boolean_data['Shower (Indoor)'] + boolean_data['Shower (Outdoor)']

In [11]:
#boolean_data.loc[0:20, 'Shower (Indoor)':'Shower (Outdoor)']

In [12]:
#boolean_data.loc[0:20,'Shower']

#boolean_data.to_csv('cleaned_boolean_features.csv')

In [13]:
raw_data.groupby('Fuel', as_index=False)['Fuel Efficiency (Highway)'].mean()

         Fuel  Fuel Efficiency (Highway)
0  Bio-Diesel                        NaN
1      Diesel                  19.571429
2    Gasoline                  18.009009
3       Other                        NaN

In [14]:
diesel_avg, gas_avg = 19.571429, 18.009009
other_avg = ((diesel_avg+gas_avg)/2)

mpg_map = {'Diesel':diesel_avg, 'Gasoline':gas_avg, 'Other':other_avg, 'Bio-Diesel':other_avg}

In [15]:
raw_data['Fuel Efficiency (Highway)'] = raw_data['Fuel Efficiency (Highway)'].fillna(raw_data['Fuel'].map(mpg_map))

In [16]:
#raw_data.loc[0:40,'Fuel':'Fuel Efficiency (Highway)']

In [17]:
modified_nonboolean_data = raw_data[['Vehicle','Price','Location','Manufacturing Year','Make & Model','Mileage','Drive',
                                      'Title Status','Transmission','Fuel','Fuel Efficiency (Highway)','Wheel Base Length',
                                      'Number of Seats with Seatbelts','Sleeping Capacity']].copy()
#modified_nonboolean_data.head(10)

In [18]:
cleaned_data = pd.concat([modified_nonboolean_data, boolean_data], axis=1, ignore_index=True)

In [19]:
#raw_data.info()

In [20]:
cols = [col for col in raw_data.columns]

cols.append('Shower')

In [21]:
cleaned_data.columns = cols

In [22]:
cleaned_data.head()

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat,Shower
0,2021 Ram Promaster City Weekender,39500.0,"107 Diversified Dr, Villa Ridge, Missouri 6308...",2021,Ram Promaster,38.0,2WD,Clean,Automatic,Gasoline,...,False,False,False,False,False,False,False,False,False,False
1,2019 4x4 2500 Mercedes Sprinter - Luxury Apart...,135000.0,"Queens, New York 11694, United States",2019,Mercedes Sprinter 2500 4x4,17000.0,4WD,Clean,Automatic,Diesel,...,False,False,False,False,False,False,False,False,False,True
2,Outside Van Family Camper,115000.0,"Granville, Ohio, United States",2014,Mercedes Benz,61500.0,2WD,Clean,Automatic,Diesel,...,True,True,True,True,True,False,False,False,False,True
3,Awesome Stealthy Adventure Van // PRICE REDUCE...,55000.0,"Murfreesboro, Tennessee, United States",2016,Ram Pro Master 2500 159 WB Diesel,39000.0,2WD,Lien,Automatic,Diesel,...,False,False,False,False,False,True,False,False,False,False
4,Beautiful 2021 Van just waiting for an artisti...,85999.0,"Nashville, Tennessee, United States",2021,2021 Dodge Ram Promaster,9065.0,2WD,Lien,Automatic,Gasoline,...,False,False,False,False,False,False,False,False,False,True

In [23]:
#cleaned_data.info()

In [24]:
cleaned_data[cleaned_data['Mileage'].isnull()]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat,Shower
24,Katie - The home on wheels by Mybushotel,120000.0,"1716 Weeping Willow Lane, Las Vegas, Nevada 89...",2021,Dodge ram promaster 3500 high roof extended,NaN,2WD,Clean,Automatic,Gasoline,...,False,False,False,False,False,False,False,False,False,True
145,THE CUSTOM by Drifter Vans,109500.0,"24175 Telegraph Road, Southfield, Michigan 480...",2021,"Sprinter, Promaster or Transit",NaN,4WD,Clean,Automatic,Gasoline,...,False,False,True,False,False,True,False,False,False,True
152,Leo - The home on wheels by Mybushotel,95000.0,"Las Vegas, Nevada, États-Unis",2021,Dodge ram promaster 2500 high roof,NaN,2WD,Clean,Automatic,Gasoline,...,False,False,True,False,True,False,False,False,False,True
156,Sara - The home on wheels by Mybushotel,90000.0,"Las Vegas, Nevada, États-Unis",2021,Dodge ram promaster 2500 high roof,NaN,2WD,Clean,Automatic,Gasoline,...,False,False,True,False,False,False,False,False,False,True
283,THE NOMADIK by Drifter Vans,79500.0,"Detroit, Michigan, United States",2021,"Sprinter, Promaster or Transit",NaN,Other,Clean,Other,Other,...,True,True,True,True,True,True,True,False,False,True

In [25]:
nan_mileage = cleaned_data[cleaned_data['Manufacturing Year']==2021]['Mileage'].mean()
nan_mileage

2831.686567164179

In [26]:
cleaned_data['Mileage'] = cleaned_data['Mileage'].fillna(nan_mileage)

In [27]:
cleaned_data.iloc[24]
#cleaned_data.iloc[145]
#cleaned_data.iloc[152]
#cleaned_data.iloc[156]
#cleaned_data.iloc[283]

Vehicle                                    Katie - The home on wheels by Mybushotel
Price                                                                      120000.0
Location                          1716 Weeping Willow Lane, Las Vegas, Nevada 89...
Manufacturing Year                                                             2021
Make & Model                            Dodge ram promaster 3500 high roof extended
Mileage                                                                 2831.686567
Drive                                                                           2WD
Title Status                                                                  Clean
Transmission                                                              Automatic
Fuel                                                                       Gasoline
Fuel Efficiency (Highway)                                                      25.0
Wheel Base Length                                                               NaN
Number of Seats with Seatbelts                                                    2
Sleeping Capacity                                                                 2
Air Bags                                                                       True
Air Conditioner                                                                True
Audio System                                                                   True
Backup Camera                                                                  True
Bluetooth / Wifi                                                               True
Cooler                                                                         True
Exterior Lights                                                               False
Fresh Water Tank (Portable)                                                    True
Inverter                                                                       True
Refrigerator                                                                   True
Roof Fan                                                                       True
Roof Rack                                                                      True
Sink                                                                           True
Solar                                                                          True
Tow Winch                                                                     False
Towing Package                                                                False
USB port                                                                       True
Bike Rack                                                                     False
Fresh Water Tank (Built-in)                                                    True
Grey / Black Water Tanks                                                       True
Heater / Furnace                                                               True
Oven                                                                           True
Security System                                                               False
Shower (Indoor)                                                                True
Shower (Outdoor)                                                               True
Stove                                                                          True
Toilet                                                                         True
Water Heater                                                                   True
Water Pump                                                                     True
Awning                                                                         True
Electric windows                                                               True
Microwave                                                                      True
Offroad Lights                                                                False
Offroad Tires                                                                 False
Skylight                                                                      False
Suspension Mods                                                               False
TV                                                                            False
Propane                                                                       False
Heated seats                                                                  False
Generator                                                                     False
Child Seat                                                                    False
Shower                                                                         True
Name: 24, dtype: object

In [28]:
#cleaned_data.info()

In [29]:
cleaned_data.to_csv('clean_data_v1.csv')

## Data Cleaning/Prep Tasks v2.0:

- [x] calculate average MPG of gasoline vehicles, and assign this value to gasoline vehicles without an MPG value
- [x] calculate average MPG of diesel vehicles, and assign this value to diesel vehicles without an MPG value
- [x] combine indoor/outdoor showers
- [x] assign False values to all boolean columns that currently have no value in a given cell
- [x] find vans without mileage listed, determine their model year, and assign a mileage value based on the average mileage of other vans from that year
- [x] update the one negative Sleeping Capacity to positive

In [30]:
cleaned_data[cleaned_data['Sleeping Capacity']<0]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat,Shower
168,Adventure Cabin - #Vanlife in a Converted Cust...,69999.0,"Orem, Utah, United States",2019,2019 Ford Transit,51000.0,2WD,Lien,Automatic,Gasoline,...,False,False,False,False,False,False,False,False,False,True

In [31]:
cleaned_data.iat[168,13]= 11

In [32]:
cleaned_data.iloc[168]['Sleeping Capacity']

11

In [33]:
cleaned_data.to_csv('clean_data_v1.csv')

In [34]:
fuel_map = {'Diesel':1, 'Gasoline':2, 'Other':3, 'Bio-Diesel':3}
cleaned_data['Fuel (Code)'] = raw_data['Fuel'].map(fuel_map)

In [35]:
#cleaned_data.info()

In [36]:
cleaned_data.to_csv('clean_data_v1.csv')

## To Do:

- [ ] convert booleans to 0/1

In [37]:
bool_cols = [col for col in boolean_data.columns]

for col in bool_cols:
    boolean_data[col] = boolean_data[col].astype(int)

In [38]:
boolean_data.head()

,Air Bags,Air Conditioner,Audio System,Backup Camera,Bluetooth / Wifi,Cooler,Exterior Lights,Fresh Water Tank (Portable),Inverter,Refrigerator,...,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat,Shower
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,1
2,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,0,0,0,0,1
3,1,0,1,1,1,0,0,1,1,1,...,0,0,0,0,0,1,0,0,0,0
4,1,1,1,1,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,1

In [39]:
cleaned_data_v2 = pd.concat([modified_nonboolean_data, boolean_data], axis=1, ignore_index=True)

In [40]:
cleaned_data_v2.columns = cols

In [41]:
cleaned_data_v2.head()

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat,Shower
0,2021 Ram Promaster City Weekender,39500.0,"107 Diversified Dr, Villa Ridge, Missouri 6308...",2021,Ram Promaster,38.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,0,0,0,0,0
1,2019 4x4 2500 Mercedes Sprinter - Luxury Apart...,135000.0,"Queens, New York 11694, United States",2019,Mercedes Sprinter 2500 4x4,17000.0,4WD,Clean,Automatic,Diesel,...,0,0,0,0,0,0,0,0,0,1
2,Outside Van Family Camper,115000.0,"Granville, Ohio, United States",2014,Mercedes Benz,61500.0,2WD,Clean,Automatic,Diesel,...,1,1,1,1,1,0,0,0,0,1
3,Awesome Stealthy Adventure Van // PRICE REDUCE...,55000.0,"Murfreesboro, Tennessee, United States",2016,Ram Pro Master 2500 159 WB Diesel,39000.0,2WD,Lien,Automatic,Diesel,...,0,0,0,0,0,1,0,0,0,0
4,Beautiful 2021 Van just waiting for an artisti...,85999.0,"Nashville, Tennessee, United States",2021,2021 Dodge Ram Promaster,9065.0,2WD,Lien,Automatic,Gasoline,...,0,0,0,0,0,0,0,0,0,1

In [42]:
cleaned_data_v2['Fuel Efficiency (Highway)'] = cleaned_data_v2['Fuel Efficiency (Highway)'].fillna(cleaned_data_v2['Fuel'].map(mpg_map))

In [43]:
#cleaned_data_v2['Fuel (Code)'] = raw_data['Fuel'].map(fuel_map)

In [44]:
cleaned_data_v2[cleaned_data_v2['Sleeping Capacity']<0]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Offroad Lights,Offroad Tires,Skylight,Suspension Mods,TV,Propane,Heated seats,Generator,Child Seat,Shower
168,Adventure Cabin - #Vanlife in a Converted Cust...,69999.0,"Orem, Utah, United States",2019,2019 Ford Transit,51000.0,2WD,Lien,Automatic,Gasoline,...,0,0,0,0,0,0,0,0,0,1

In [45]:
cleaned_data_v2.iat[168,13] = 11

In [46]:
cleaned_data_v2.iloc[168]['Sleeping Capacity']

11

In [47]:
cleaned_data_v2['Mileage'] = cleaned_data_v2['Mileage'].fillna(nan_mileage)

In [48]:
cleaned_data_v2.to_csv('clean_data_v2.csv')

A function to clean a dataframe needs to:

- [ ] Drop Handicap Access and 'Unnamed: 0' 
- [ ] Split data into boolean and non-boolean columns
- [ ] Boolean data needs to have all NaN's filled with False, combine Indoor/Outdoor showers, and translate T/F to 1/0
- [ ] Fuel efficiency average needs to be calculated for each fuel-type, and the respective values added to MPG NaNs
- [ ] The two dataframes need to be concatenated, and the column names fixed
- [ ] NaNs in vehicle mileage need to be filled in with the average value from that model year
- [ ] Negative values in Sleeping capacity need to be corrected
- [ ] Fuel type needs to be numerically ranked
- [ ] Drop all duplicate columns (subset on 'Price' + 'Location' + 'Make & Model'

In [49]:
raw_data2 = pd.read_csv('vanlifetrader_data_oct28.csv')
raw_data3 = pd.read_csv('vanlifetrader_data.csv')

In [50]:
expanded_data = pd.merge(left=raw_data2, right=raw_data3, how='outer')

In [51]:
#expanded_data.info()

In [52]:
expanded_data.drop_duplicates(subset=['Price', 'Location', 'Make & Model'], keep='first', inplace=True)

In [53]:
#expanded_data.info()

In [54]:
expanded_data.drop(columns=['Unnamed: 0','Handicap / Wheelchair Conversion'], inplace=True)

In [55]:
expanded_data.groupby('Fuel', as_index=False)['Fuel Efficiency (Highway)'].mean()

         Fuel  Fuel Efficiency (Highway)
0  Bio-Diesel                        NaN
1      Diesel                  19.655462
2    Gasoline                  17.761538
3       Other                        NaN

In [56]:
# use df.groupby('Fuel', as_index=False)['Fuel Efficiency (Highway)'].mean() to find MPG avgs by fuel type for inputs

def data_cleaner(df, diesel_avg, gas_avg, other_avg):
    
    mpg_map = {'Diesel':diesel_avg, 'Gasoline':gas_avg, 'Other':other_avg, 'Bio-Diesel':other_avg}
    cols = [col for col in df.columns]
    cols.append('Shower')
    fuel_map = {'Diesel':1, 'Gasoline':2, 'Other':3, 'Bio-Diesel':3}
    #filename = input('Please input a filename for the .csv output:')
    
    # split into boolean and nonboolean dfs
    boolean_split = df.drop(columns=['Vehicle','Price','Location','Manufacturing Year','Make & Model','Mileage','Drive',
                                      'Title Status','Transmission','Fuel','Fuel Efficiency (Highway)','Wheel Base Length',
                                      'Number of Seats with Seatbelts','Sleeping Capacity'])
    nonboolean_split = df[['Vehicle','Price','Location','Manufacturing Year','Make & Model','Mileage','Drive',
                                      'Title Status','Transmission','Fuel','Fuel Efficiency (Highway)','Wheel Base Length',
                                      'Number of Seats with Seatbelts','Sleeping Capacity']].copy()
    
    # fill NaN's in boolean_split
    boolean_split.fillna(False, inplace=True)
    
    # create Showers column in boolean_split
    boolean_split['Shower'] = boolean_split['Shower (Indoor)'] + boolean_split['Shower (Outdoor)']
    
    # convert T/F to 1/0
    bool_cols = [col for col in boolean_split.columns]

    for col in bool_cols:
        boolean_split[col] = boolean_split[col].astype(int)
    
    # find missing values for MPG and fill them
    nonboolean_split['Fuel Efficiency (Highway)'] = raw_data['Fuel Efficiency (Highway)'].fillna(raw_data['Fuel'].map(mpg_map))
    
    # concatenate dfs
    cleaned_data_v3 = pd.concat([nonboolean_split, boolean_split], axis=1, ignore_index=True)
    cleaned_data_v3.columns = cols
    
    # code the fuel types
    cleaned_data_v3['Fuel (Code)'] = df['Fuel'].map(fuel_map)
    
    print('I made a dataframe for you. It would be wise to check the Sleeping Capacity and Mileage columns for negatives and NaNs.')
    print('On second thought, here are the outputs of those columns, in case you need to fix anything:')
    print('Use "nan_mileage = df[df["Manufacturing Year"]=="YEAR"]["Mileage"].mean()" to find average mileages for each model year that is currently NaN.')
    print('Make sure to change the double quotes to single quotes.')
    print('Use df.iat[168,13] = NUMBER to change SLeeping Capacity values, and check with df.iloc[ROW#].')
    #clean_data_v3.to_csv(filename)
    return cleaned_data_v3

In [57]:
clean_data_v3 = data_cleaner(expanded_data, 19.655462, 17.761538, (19.655462+17.761538)/2)

I made a dataframe for you. It would be wise to check the Sleeping Capacity and Mileage columns for negatives and NaNs.
On second thought, here are the outputs of those columns, in case you need to fix anything:
Use "nan_mileage = df[df["Manufacturing Year"]=="YEAR"]["Mileage"].mean()" to find average mileages for each model year that is currently NaN.
Make sure to change the double quotes to single quotes.
Use df.iat[168,13] = NUMBER to change SLeeping Capacity values, and check with df.iloc[ROW#].

In [58]:
#clean_data_v3.to_csv('clean_data_v3.csv')
clean_data_v3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 593 entries, 0 to 1028
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Vehicle                         593 non-null    object
 1   Price                           593 non-null    float64
 2   Location                        593 non-null    object
 3   Manufacturing Year              593 non-null    int64
 4   Make & Model                    593 non-null    object
 5   Mileage                         588 non-null    float64
 6   Drive                           593 non-null    object
 7   Title Status                    593 non-null    object
 8   Transmission                    593 non-null    object
 9   Fuel                            593 non-null    object
 10  Fuel Efficiency (Highway)       508 non-null    float64
 11  Wheel Base Length               413 non-null    float64
 12  Number of Seats with Seatbelts  593 non-null    int64
 13  Sleeping Capacity               593 non-null    int64
 14  Air Bags                        593 non-null    int64
 15  Air Conditioner                 593 non-null    int64
 16  Audio System                    593 non-null    int64
 17  Backup Camera                   593 non-null    int64
 18  Bluetooth / Wifi                593 non-null    int64
 19  Electric windows                593 non-null    int64
 20  Exterior Lights                 593 non-null    int64
 21  Fresh Water Tank (Portable)     593 non-null    int64
 22  Generator                       593 non-null    int64
 23  Grey / Black Water Tanks        593 non-null    int64
 24  Heater / Furnace                593 non-null    int64
 25  Inverter                        593 non-null    int64
 26  Refrigerator                    593 non-null    int64
 27  Roof Fan                        593 non-null    int64
 28  Roof Rack                       593 non-null    int64
 29  Shower (Outdoor)                593 non-null    int64
 30  Sink                            593 non-null    int64
 31  Solar                           593 non-null    int64
 32  Toilet                          593 non-null    int64
 33  USB port                        593 non-null    int64
 34  Water Heater                    593 non-null    int64
 35  Water Pump                      593 non-null    int64
 36  Fresh Water Tank (Built-in)     593 non-null    int64
 37  Shower (Indoor)                 593 non-null    int64
 38  Stove                           593 non-null    int64
 39  Towing Package                  593 non-null    int64
 40  Heated seats                    593 non-null    int64
 41  Offroad Lights                  593 non-null    int64
 42  Awning                          593 non-null    int64
 43  Cooler                          593 non-null    int64
 44  Offroad Tires                   593 non-null    int64
 45  Security System                 593 non-null    int64
 46  Suspension Mods                 593 non-null    int64
 47  Tow Winch                       593 non-null    int64
 48  Oven                            593 non-null    int64
 49  Propane                         593 non-null    int64
 50  Skylight                        593 non-null    int64
 51  Bike Rack                       593 non-null    int64
 52  Child Seat                      593 non-null    int64
 53  Microwave                       593 non-null    int64
 54  TV                              593 non-null    int64
 55  Shower                          593 non-null    int64
 56  Fuel (Code)                     593 non-null    int64
dtypes: float64(4), int64(46), object(7)
memory usage: 268.7+ KB

In [59]:
clean_data_v3[clean_data_v3['Sleeping Capacity']<0]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Tow Winch,Oven,Propane,Skylight,Bike Rack,Child Seat,Microwave,TV,Shower,Fuel (Code)
197,Adventure Cabin - #Vanlife in a Converted Cust...,69999.0,"Orem, Utah, United States",2019,2019 Ford Transit,51000.0,2WD,Lien,Automatic,Gasoline,...,0,0,0,0,1,0,0,0,1,2

In [60]:
clean_data_v3.iloc[196]['Sleeping Capacity']

-11

In [61]:
clean_data_v3.iat[196,13] = 11

In [62]:
clean_data_v3.iloc[196]['Sleeping Capacity']

11

In [63]:
clean_data_v3[clean_data_v3['Mileage'].isnull()]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Tow Winch,Oven,Propane,Skylight,Bike Rack,Child Seat,Microwave,TV,Shower,Fuel (Code)
56,Katie - The home on wheels by Mybushotel,120000.0,"1716 Weeping Willow Lane, Las Vegas, Nevada 89...",2021,Dodge ram promaster 3500 high roof extended,NaN,2WD,Clean,Automatic,Gasoline,...,0,1,0,0,0,0,1,0,1,2
175,THE CUSTOM by Drifter Vans,109500.0,"24175 Telegraph Road, Southfield, Michigan 480...",2021,"Sprinter, Promaster or Transit",NaN,4WD,Clean,Automatic,Gasoline,...,0,0,1,1,0,0,0,0,1,2
182,Leo - The home on wheels by Mybushotel,95000.0,"Las Vegas, Nevada, États-Unis",2021,Dodge ram promaster 2500 high roof,NaN,2WD,Clean,Automatic,Gasoline,...,0,0,0,1,0,0,1,1,1,2
186,Sara - The home on wheels by Mybushotel,90000.0,"Las Vegas, Nevada, États-Unis",2021,Dodge ram promaster 2500 high roof,NaN,2WD,Clean,Automatic,Gasoline,...,0,0,0,1,0,0,0,0,1,2
312,THE NOMADIK by Drifter Vans,79500.0,"Detroit, Michigan, United States",2021,"Sprinter, Promaster or Transit",NaN,Other,Clean,Other,Other,...,1,0,1,1,0,0,0,1,1,3

In [64]:
clean_data_v3['Mileage'] = clean_data_v3['Mileage'].fillna(nan_mileage)

In [65]:
#clean_data_v3.to_csv('clean_data_v3.csv')

In [66]:
clean_data_v3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 593 entries, 0 to 1028
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Vehicle                         593 non-null    object
 1   Price                           593 non-null    float64
 2   Location                        593 non-null    object
 3   Manufacturing Year              593 non-null    int64
 4   Make & Model                    593 non-null    object
 5   Mileage                         593 non-null    float64
 6   Drive                           593 non-null    object
 7   Title Status                    593 non-null    object
 8   Transmission                    593 non-null    object
 9   Fuel                            593 non-null    object
 10  Fuel Efficiency (Highway)       508 non-null    float64
 11  Wheel Base Length               413 non-null    float64
 12  Number of Seats with Seatbelts  593 non-null    int64
 13  Sleeping Capacity               593 non-null    int64
 14  Air Bags                        593 non-null    int64
 15  Air Conditioner                 593 non-null    int64
 16  Audio System                    593 non-null    int64
 17  Backup Camera                   593 non-null    int64
 18  Bluetooth / Wifi                593 non-null    int64
 19  Electric windows                593 non-null    int64
 20  Exterior Lights                 593 non-null    int64
 21  Fresh Water Tank (Portable)     593 non-null    int64
 22  Generator                       593 non-null    int64
 23  Grey / Black Water Tanks        593 non-null    int64
 24  Heater / Furnace                593 non-null    int64
 25  Inverter                        593 non-null    int64
 26  Refrigerator                    593 non-null    int64
 27  Roof Fan                        593 non-null    int64
 28  Roof Rack                       593 non-null    int64
 29  Shower (Outdoor)                593 non-null    int64
 30  Sink                            593 non-null    int64
 31  Solar                           593 non-null    int64
 32  Toilet                          593 non-null    int64
 33  USB port                        593 non-null    int64
 34  Water Heater                    593 non-null    int64
 35  Water Pump                      593 non-null    int64
 36  Fresh Water Tank (Built-in)     593 non-null    int64
 37  Shower (Indoor)                 593 non-null    int64
 38  Stove                           593 non-null    int64
 39  Towing Package                  593 non-null    int64
 40  Heated seats                    593 non-null    int64
 41  Offroad Lights                  593 non-null    int64
 42  Awning                          593 non-null    int64
 43  Cooler                          593 non-null    int64
 44  Offroad Tires                   593 non-null    int64
 45  Security System                 593 non-null    int64
 46  Suspension Mods                 593 non-null    int64
 47  Tow Winch                       593 non-null    int64
 48  Oven                            593 non-null    int64
 49  Propane                         593 non-null    int64
 50  Skylight                        593 non-null    int64
 51  Bike Rack                       593 non-null    int64
 52  Child Seat                      593 non-null    int64
 53  Microwave                       593 non-null    int64
 54  TV                              593 non-null    int64
 55  Shower                          593 non-null    int64
 56  Fuel (Code)                     593 non-null    int64
dtypes: float64(4), int64(46), object(7)
memory usage: 268.7+ KB

In [67]:
mpg_map = {'Diesel':19.655462, 'Gasoline':17.761538, 'Other':(19.655462+17.761538)/2, 'Bio-Diesel':(19.655462+17.761538)/2}

clean_data_v3['Fuel Efficiency (Highway)'] = clean_data_v3['Fuel Efficiency (Highway)'].fillna(clean_data_v3['Fuel'].map(mpg_map))

In [68]:
clean_data_v3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 593 entries, 0 to 1028
Data columns (total 57 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Vehicle                         593 non-null    object
 1   Price                           593 non-null    float64
 2   Location                        593 non-null    object
 3   Manufacturing Year              593 non-null    int64
 4   Make & Model                    593 non-null    object
 5   Mileage                         593 non-null    float64
 6   Drive                           593 non-null    object
 7   Title Status                    593 non-null    object
 8   Transmission                    593 non-null    object
 9   Fuel                            593 non-null    object
 10  Fuel Efficiency (Highway)       593 non-null    float64
 11  Wheel Base Length               413 non-null    float64
 12  Number of Seats with Seatbelts  593 non-null    int64
 13  Sleeping Capacity               593 non-null    int64
 14  Air Bags                        593 non-null    int64
 15  Air Conditioner                 593 non-null    int64
 16  Audio System                    593 non-null    int64
 17  Backup Camera                   593 non-null    int64
 18  Bluetooth / Wifi                593 non-null    int64
 19  Electric windows                593 non-null    int64
 20  Exterior Lights                 593 non-null    int64
 21  Fresh Water Tank (Portable)     593 non-null    int64
 22  Generator                       593 non-null    int64
 23  Grey / Black Water Tanks        593 non-null    int64
 24  Heater / Furnace                593 non-null    int64
 25  Inverter                        593 non-null    int64
 26  Refrigerator                    593 non-null    int64
 27  Roof Fan                        593 non-null    int64
 28  Roof Rack                       593 non-null    int64
 29  Shower (Outdoor)                593 non-null    int64
 30  Sink                            593 non-null    int64
 31  Solar                           593 non-null    int64
 32  Toilet                          593 non-null    int64
 33  USB port                        593 non-null    int64
 34  Water Heater                    593 non-null    int64
 35  Water Pump                      593 non-null    int64
 36  Fresh Water Tank (Built-in)     593 non-null    int64
 37  Shower (Indoor)                 593 non-null    int64
 38  Stove                           593 non-null    int64
 39  Towing Package                  593 non-null    int64
 40  Heated seats                    593 non-null    int64
 41  Offroad Lights                  593 non-null    int64
 42  Awning                          593 non-null    int64
 43  Cooler                          593 non-null    int64
 44  Offroad Tires                   593 non-null    int64
 45  Security System                 593 non-null    int64
 46  Suspension Mods                 593 non-null    int64
 47  Tow Winch                       593 non-null    int64
 48  Oven                            593 non-null    int64
 49  Propane                         593 non-null    int64
 50  Skylight                        593 non-null    int64
 51  Bike Rack                       593 non-null    int64
 52  Child Seat                      593 non-null    int64
 53  Microwave                       593 non-null    int64
 54  TV                              593 non-null    int64
 55  Shower                          593 non-null    int64
 56  Fuel (Code)                     593 non-null    int64
dtypes: float64(4), int64(46), object(7)
memory usage: 268.7+ KB

In [69]:
clean_data_v3.to_csv('clean_data_v3.csv')

In [70]:
clean_data_v3['Make & Model'][2]

'Sprinter'

In [71]:
# Create dummy variables for four different models

for i in range(len(clean_data_v3['Make & Model'])):
    current_model = clean_data_v3['Make & Model'].iloc[i]
    current_vehicle = clean_data_v3['Vehicle'].iloc[i]
    s = 'SPRINTER'
    p = 'PROMASTER'
    t = 'TRANSIT'
    o = 'Other'
    
    if s in str(current_model).upper() or s in str(current_vehicle).upper():
        clean_data_v3.iat[i,4] = 'Sprinter'
    elif p in str(current_model).upper() or p in str(current_vehicle).upper():
        clean_data_v3.iat[i,4] = 'Promaster' 
    elif t in str(current_model).upper() or t in str(current_vehicle).upper():
        clean_data_v3.iat[i,4] = 'Transit'
    else:
        clean_data_v3.iat[i,4] = o
    
    current = ''

In [72]:
clean_data_v3.to_csv('clean_data_v3.csv')

In [73]:
# make the dummies, actually

sprinter_dict = {'Sprinter': 1, 'Promaster': 0, 'Transit': 0, 'Other': 0}
clean_data_v3['Sprinter'] = clean_data_v3['Make & Model'].map(sprinter_dict)

promaster_dict = {'Sprinter': 0, 'Promaster': 1, 'Transit': 0, 'Other': 0}
clean_data_v3['Promaster'] = clean_data_v3['Make & Model'].map(promaster_dict)

transit_dict = {'Sprinter': 0, 'Promaster': 0, 'Transit': 1, 'Other': 0}
clean_data_v3['Transit'] = clean_data_v3['Make & Model'].map(transit_dict)

other_dict = {'Sprinter': 0, 'Promaster': 0, 'Transit': 0, 'Other': 1}
clean_data_v3['Other'] = clean_data_v3['Make & Model'].map(other_dict)

In [74]:
#pd.get_dummies(clean_data_v3['Make & Model'], drop_first = True)

In [75]:
clean_data_v3['Wheel Base Length'].value_counts()

 144.0     112
 159.0      99
 170.0      89
 148.0      41
 136.0      26
 158.0       7
 118.0       7
 140.0       4
 130.0       3
 138.0       2
 146.0       2
 350.0       2
 59.0        2
 120.0       1
 145.0       1
 171.0       1
 132.0       1
 0.0         1
 121.0       1
 178.0       1
 15.0        1
 1.0         1
-144.0       1
 17.0        1
 19.0        1
 156.0       1
 21.0        1
 126.0       1
 18.0        1
 1559.0      1
Name: Wheel Base Length, dtype: int64

In [76]:
clean_data_v3[clean_data_v3['Wheel Base Length']==0]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Bike Rack,Child Seat,Microwave,TV,Shower,Fuel (Code),Sprinter,Promaster,Transit,Other
518,2019 Ford Transit 250 Medium Roof - 3.5L EcoBo...,45000.0,"Lincoln, Nebraska, United States",2019,Transit,23000.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,0,1,0

In [77]:
clean_data_v3[clean_data_v3['Wheel Base Length']<0]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Bike Rack,Child Seat,Microwave,TV,Shower,Fuel (Code),Sprinter,Promaster,Transit,Other
189,ONE OF A KIND OFF-GRID SPRINTER VAN,99000.0,"Vermont, United States",2017,Sprinter,20000.0,2WD,Clean,Automatic,Diesel,...,0,0,0,0,1,1,1,0,0,0

In [78]:
clean_data_v3.iat[188,11]=144
clean_data_v3.iloc[188,9:16]

Fuel                                 Diesel
Fuel Efficiency (Highway)         19.571429
Wheel Base Length                     144.0
Number of Seats with Seatbelts            2
Sleeping Capacity                         2
Air Bags                                  1
Air Conditioner                           0
Name: 189, dtype: object

In [79]:
clean_data_v3['Wheel Base Length'] = clean_data_v3['Wheel Base Length'].fillna(0)

In [80]:
clean_data_v3[clean_data_v3['Wheel Base Length']==0]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Bike Rack,Child Seat,Microwave,TV,Shower,Fuel (Code),Sprinter,Promaster,Transit,Other
5,SKOOLIANA 5 WINDOW WHEEL CHAIR DOOR SHORT BUS,45000.0,"Eugene, Oregon, United States",2003,Other,162000.0,2WD,Clean,Automatic,Diesel,...,0,0,0,0,1,1,0,0,0,1
10,NEW BUILD Ford Transit van conversion,69000.0,"San Diego, California, United States",2018,Transit,65000.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,0,1,0
14,2020 Ford Transit AWD 4 Seater,129900.0,"Villa Ridge, Missouri, United States",2020,Transit,1300.0,AWD,Clean,Automatic,Gasoline,...,0,0,1,0,0,2,0,0,1,0
18,Immediate Build Date Opening!,85000.0,"Chicago, Illinois, United States",2019,Sprinter,0.0,Other,Clean,Automatic,Diesel,...,0,0,0,0,1,1,1,0,0,0
20,2019 Mercedes 2500 sprinter van 4x4,105200.0,"832 Oregon Avenue, Linthicum, Maryland 21090, ...",2019,Sprinter,19319.0,4WD,Clean,Automatic,Diesel,...,1,0,0,0,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,2015 Ford Transit Custom Camper high roof exte...,54000.0,"V7H 2E9, North Vancouver, British Columbia, Ca...",2015,Transit,80700.0,2WD,Clean,Automatic,Gasoline,...,1,0,0,0,1,2,0,0,1,0
931,(SALE PENDING) 2010 Freightliner Sprinter,55000.0,"Portland, Oregon, United States",2010,Sprinter,191000.0,2WD,Clean,Automatic,Diesel,...,0,0,0,0,0,1,1,0,0,0
966,Cozy Family Van (sleeps 4) built by Inner Space,85000.0,"El Sobrante, California, United States",2019,Promaster,30000.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
1025,Converted Ambulance/RV/Toyhauler/TinyHome/Boon...,60000.0,"2607 Railroad Street West, Missoula, Montana 5...",1996,Other,76000.0,2WD,Clean,Automatic,Diesel,...,1,0,0,1,1,1,0,0,0,1
1026,converted camper van,12000.0,"New Jersey, United States",1994,Other,195000.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,0,0,1

In [81]:
clean_data_v3['Wheel Base Length'].value_counts()

0.0       181
144.0     113
159.0      99
170.0      89
148.0      41
136.0      26
158.0       7
118.0       7
140.0       4
130.0       3
59.0        2
146.0       2
138.0       2
350.0       2
132.0       1
121.0       1
178.0       1
171.0       1
145.0       1
1.0         1
18.0        1
17.0        1
156.0       1
21.0        1
120.0       1
126.0       1
19.0        1
15.0        1
1559.0      1
Name: Wheel Base Length, dtype: int64

In [82]:
#transit_wheelbase_map = {'Transit':148}
#clean_data_v3[(clean_data_v3['Wheel Base Length']==0) & (clean_data_v3['Make & Model']=='Transit')]

cond_transit = (clean_data_v3['Wheel Base Length']==0) & (clean_data_v3['Make & Model']=='Transit')
replace_transit = 148
clean_data_v3['Wheel Base Length'].mask(cond_transit,replace_transit,inplace=True)

In [83]:
clean_data_v3['Wheel Base Length'].value_counts()

0.0       148
144.0     113
159.0      99
170.0      89
148.0      74
136.0      26
158.0       7
118.0       7
140.0       4
130.0       3
59.0        2
146.0       2
138.0       2
350.0       2
132.0       1
121.0       1
178.0       1
171.0       1
145.0       1
1.0         1
18.0        1
17.0        1
156.0       1
21.0        1
120.0       1
126.0       1
19.0        1
15.0        1
1559.0      1
Name: Wheel Base Length, dtype: int64

In [84]:
clean_data_v3[(clean_data_v3['Wheel Base Length']==0) & (clean_data_v3['Make & Model']=='Promaster')]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Bike Rack,Child Seat,Microwave,TV,Shower,Fuel (Code),Sprinter,Promaster,Transit,Other
25,2021 PROMASTER LUXURY VAN shower & toilet,120000.0,"Нортридж, Калифорния, Соединённые Штаты Америки",2021,Promaster,7000.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
37,Luxury NEW & LOW MILAGE Beautiful Conversion C...,50000.0,"Huntington Beach, California, United States",2019,Promaster,56000.000000,2WD,Clean,Automatic,Gasoline,...,1,0,0,0,0,2,0,1,0,0
54,2020 RAM Promaster RV Elevation Road,31999.0,"200 Gabbard Way, Mount Orab, Ohio 45154, Unite...",2020,Promaster,250.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
56,Katie - The home on wheels by Mybushotel,120000.0,"1716 Weeping Willow Lane, Las Vegas, Nevada 89...",2021,Promaster,2831.686567,2WD,Clean,Automatic,Gasoline,...,0,0,1,0,1,2,0,1,0,0
67,Beautiful Simple Promaster,75000.0,"1455 West Cedar Avenue, Denver, Colorado 80223...",2021,Promaster,500.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
92,RAM PROMASTER 2500 HIGH TOP,96876.0,"Rochester, New York, United States",2021,Promaster,20.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
117,Professionally Built 2016 Ram High Roof 159” P...,80000.0,"Boise, Idaho, United States",2016,Promaster,74087.000000,2WD,Clean,Automatic,Diesel,...,0,1,0,0,1,1,0,1,0,0
144,Badger - A Cozy Promaster City Van Conversion,33998.0,"Boston, Massachusetts, United States",2016,Promaster,54000.000000,2WD,Clean,Automatic,Gasoline,...,0,1,0,0,0,2,0,1,0,0
149,2019 Ram ProMaster 1500 with Professional Conv...,54500.0,"Baltimore, Maryland, United States",2019,Promaster,72000.000000,2WD,Lien,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
167,Built for Offgrid Adventures,82000.0,"Eureka Springs, Arkansas 72632, United States",2021,Promaster,1000.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
173,2019 Promaster 3500 extended with Full Bath | ...,95000.0,"Sacramento, California, United States",2019,Promaster,23900.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
186,Sara - The home on wheels by Mybushotel,90000.0,"Las Vegas, Nevada, États-Unis",2021,Promaster,2831.686567,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
219,The Wandering Family Van!,127500.0,"Colorado, United States",2021,Promaster,2000.000000,2WD,Clean,Automatic,Gasoline,...,0,1,0,0,1,2,0,1,0,0
229,2021 promaster cozy cottage,79900.0,"Naples, Florida, United States",2021,Promaster,8000.000000,2WD,Lien,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
254,"2017 Ram Promaster 2500, 159.",50000.0,"Бруклин, Нью-Йорк, Соединённые Штаты Америки",2017,Promaster,176000.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
289,2021 Craft Autoworks Scout Adventure Van,64900.0,"Reno, Nevada, United States",2021,Promaster,100.000000,2WD,Clean,Automatic,Gasoline,...,1,0,0,0,1,2,0,1,0,0
291,Beautiful 3500 Promaster with luxury Fridge an...,89000.0,"730 N Grandview Ave, Covina, California 91723,...",2014,Promaster,60509.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
336,Off Grid 3500 Promaster,82000.0,"North Melrose Drive, Vista, California 92083, ...",2019,Promaster,19025.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
351,2021 Promaster 3500 extended Campervan,89500.0,"3972 Bach Buxton Road, Cincinnati, Ohio 45102,...",2021,Promaster,300.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
438,Conversion Van for sale by owner,67000.0,"Dripping Springs, Texas",2018,Promaster,1450.000000,AWD,Clean,Automatic,Gasoline,...,0,0,0,1,0,2,0,1,0,0
450,2020 RAM ProMaster 1500 high roof Low mileage,75000.0,"Сан-Диего, Калифорния, Соединённые Штаты Америки",2020,Promaster,1050.000000,2WD,Clean,Automatic,Gasoline,...,0,1,0,0,0,2,0,1,0,0
453,RAM PROMASTER High Roof Fully Equipped Air Con...,79500.0,"1004 Cherry Valley Boulevard, Calimesa, Califo...",2017,Promaster,73000.000000,2WD,Clean,Automatic,Gasoline,...,1,0,1,1,1,2,0,1,0,0
472,"Promaster - 2018, high roof, clean title",68900.0,"Dublin, Ohio 43016, United States",2018,Promaster,49000.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
499,2019 Conversion Van for 2,30000.0,"Carlisle, Iowa 50047, United States",2019,Promaster,10000.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
660,New Offgrid 2021 ProMaster,89900.0,"Eureka Springs, Arkansas 72632, United States",2021,Promaster,1000.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
865,Fully decked-out RAM ProMaster with tiny-home ...,105000.0,"Lafayette, Colorado, United States",2017,Promaster,9500.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0
966,Cozy Family Van (sleeps 4) built by Inner Space,85000.0,"El Sobrante, California, United States",2019,Promaster,30000.000000,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,1,2,0,1,0,0

In [85]:
cond_promaster = (clean_data_v3['Wheel Base Length']==0) & (clean_data_v3['Make & Model']=='Promaster')
replace_promaster = 159
clean_data_v3['Wheel Base Length'].mask(cond_promaster,replace_promaster,inplace=True)

In [86]:
cond_sprinter = (clean_data_v3['Wheel Base Length']==0) & (clean_data_v3['Make & Model']=='Sprinter')
replace_sprinter = 144
clean_data_v3['Wheel Base Length'].mask(cond_sprinter,replace_sprinter,inplace=True)

In [87]:
clean_data_v3[clean_data_v3['Wheel Base Length']<100]

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Bike Rack,Child Seat,Microwave,TV,Shower,Fuel (Code),Sprinter,Promaster,Transit,Other
5,SKOOLIANA 5 WINDOW WHEEL CHAIR DOOR SHORT BUS,45000.0,"Eugene, Oregon, United States",2003,Other,162000.0,2WD,Clean,Automatic,Diesel,...,0,0,0,0,1,1,0,0,0,1
21,The White Elephant,39000.0,"Grand Rapids, Michigan, United States",1999,Other,160000.0,2WD,Clean,Automatic,Diesel,...,0,0,0,0,0,1,0,0,0,1
45,FULLY LOADED VW WESTFALIA *NEW Engine/Interior...,50000.0,"Irvine, California, United States",1982,Other,3000.0,2WD,Clean,Manual (Stick Shift),Gasoline,...,0,0,0,0,0,2,0,0,0,1
52,2002 VW Eurovan Weekender Westfalia,27000.0,"Long Beach, California, United States",2002,Other,213000.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,0,0,1
53,2021 Ram Promaster City Weekender,39500.0,"107 Diversified Dr, Villa Ridge, Missouri 6308...",2021,Promaster,38.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,Fully converted 2013 Ford E-150,21000.0,"Venice, Florida, United States",2013,Other,107500.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,0,0,1
908,SKOOLIANA 5 WINDOW WHEEL CHAIR DOOR SHORT BUS,55000.0,"Eugene, Oregon, United States",2003,Other,162000.0,2WD,Clean,Automatic,Diesel,...,0,0,0,0,1,1,0,0,0,1
924,2017 GMC Savana Explorer SE Limited 2500 Conve...,64997.0,"Clearwater, Minnesota 55320, United States",2017,Other,6007.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,0,0,1
1025,Converted Ambulance/RV/Toyhauler/TinyHome/Boon...,60000.0,"2607 Railroad Street West, Missoula, Montana 5...",1996,Other,76000.0,2WD,Clean,Automatic,Diesel,...,1,0,0,1,1,1,0,0,0,1
1026,converted camper van,12000.0,"New Jersey, United States",1994,Other,195000.0,2WD,Clean,Automatic,Gasoline,...,0,0,0,0,0,2,0,0,0,1

In [88]:
clean_data_v3['Wheel Base Length'].mean()

131.10118043844858

In [89]:
cond_other = (clean_data_v3['Wheel Base Length']==0)
replace_other = 131
clean_data_v3['Wheel Base Length'].mask(cond_other,replace_other,inplace=True)

In [90]:
#clean_data_v3.info()

In [91]:
manufacturing_year_bins = [0,2001,2015,2020,2021]
labels = ['Old','Midlife','Newer','Brand New']
clean_data_v3['Manufacturing Year Binned'] = pd.cut(clean_data_v3['Manufacturing Year'], manufacturing_year_bins, labels=labels)

In [92]:
manufacturing_year_ordination = {"Old":1, "Midlife":2, "Newer":3, "Brand New":4}
clean_data_v3["Age"] = clean_data_v3["Manufacturing Year Binned"].replace(manufacturing_year_ordination)

In [93]:
#clean_data_v3.info()

In [94]:
wheelbase_bins = [0,150,169,2000]
labels = ['Small','Mid Size','Big']
clean_data_v3['Wheelbase Binned'] = pd.cut(clean_data_v3['Wheel Base Length'], wheelbase_bins, labels=labels)

wheelbase_ordination = {"Small":1, "Mid Size":2, "Big":3}
clean_data_v3["Size"] = clean_data_v3["Wheelbase Binned"].replace(wheelbase_ordination)

In [95]:
#clean_data_v3.to_csv('clean_data_v5.csv')
test = clean_data_v3['Location'].iloc[51].split()
test_2 = test[-3]

test2 = str(test)

test2

"['New', 'York,', 'United', 'States']"

In [96]:
western = ['Arizona', 'Colorado', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Utah', 'Wyoming', 'Alaska', 'California', 'Hawaii', 'Oregon', 'Washington']
midwest = ['Illinois', 'Indiana', 'Michigan', 'Ohio', 'Wisconsin', 'Iowa', 'Kansas', 'Minnesota', 'Missouri', 'Nebraska', 'North Dakota', 'South Dakota']
south = ['Delaware', 'Florida', 'Georgia', 'Maryland', 'North Carolina', 'South Carolina', 'Virginia', 'Washington, D.C.', 'West Virginia', 
         'Alabama', 'Kentucky', 'Mississippi', 'Tennessee','Arkansas', 'Louisiana', 'Oklahoma', 'Texas']
northeast = ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 'Rhode Island', 'Vermont','New Jersey', 'New York', 'Pennsylvania']

len(clean_data_v3['Location'])

593

In [97]:
# Create dummy variables for four different regions
double_names = ['Mexico', 'Dakota','Carolina','D.C.','Virginia','Hampshire','Island','Jersey,','York,', 'York', 'Jersey', 'Carolina,', 'Mexico,', 'Dakota,', 'Hampshire,',
               'Virginia,', 'D.C.,','Island,']
double_directions = ['New','Rhode','South','North','West','Washington']

#for i in range(len(clean_data_v3['Location'])):
for i in range(593):
    #print(i)
    current_loc = clean_data_v3['Location'].iloc[i].split()
    #state = current_loc[-3]
    
    for word in current_loc:
        word_index = 0
        next_word = ''
        
        if word in double_directions:
            word_index = current_loc.index(word)
            word_index += 1
            next_word = current_loc[word_index]
            
            if next_word in double_names:
                current_loc.append(word + " " + next_word)
                print(current_loc)
    
    current_loc_str = str(current_loc)
    
    if any(state in current_loc_str for state in western):
        clean_data_v3.iat[i,2] = 'West'
    elif any(state in current_loc_str for state in midwest):
        clean_data_v3.iat[i,2] = 'Midwest' 
    elif any(state in current_loc_str for state in south):
        clean_data_v3.iat[i,2] = 'South' 
    elif any(state in current_loc_str for state in northeast):
        clean_data_v3.iat[i,2] = 'Northeast'
    else:
        clean_data_v3.iat[i,2] = 'International'
    
    current = ''

['10', 'Via', 'Vecino,', 'Santa', 'Fe,', 'New', 'Mexico', '87506,', 'United', 'States', 'New Mexico']
['Roanoke', 'Rapids,', 'North', 'Carolina', '27870,', 'United', 'States', 'North Carolina']
['8595', 'Cox', 'Lane,', 'Cutchogue,', 'New', 'York', '11935,', 'United', 'States', 'New York']
['New', 'York,', 'United', 'States', 'New York,']
['Robbinsville', 'Township,', 'New', 'Jersey,', 'United', 'States', 'New Jersey,']
['Charleston,', 'South', 'Carolina,', 'United', 'States', 'South Carolina,']
['New', 'Jersey,', 'United', 'States', 'New Jersey,']
['Asheville,', 'North', 'Carolina,', 'United', 'States', 'North Carolina,']
['Williston,', 'North', 'Dakota,', 'United', 'States', 'North Dakota,']
['Rochester,', 'New', 'York,', 'United', 'States', 'New York,']
['Pomona,', 'New', 'York', 'New York']
['7675', 'Tega', 'Cay', 'Drive,', 'Tega', 'Cay,', 'South', 'Carolina', '29708,', 'United', 'States', 'South Carolina']
['Yonkers,', 'New', 'York,', 'United', 'States', 'New York,']
['Southport-Supply', 'Road', 'Southeast,', 'Southport,', 'North', 'Carolina', '28461,', 'United', 'States', 'North Carolina']
['Saratoga', 'Springs,', 'New', 'York,', 'United', 'States', 'New York,']
['Mount', 'Pleasant,', 'South', 'Carolina', '29464,', 'United', 'States', 'South Carolina']
['Toms', 'River,', 'New', 'Jersey', '08753,', 'United', 'States', 'New Jersey']
['Winston-Salem,', 'North', 'Carolina,', 'United', 'States', 'North Carolina,']
['Binghamton,', 'New', 'York,', 'United', 'States', 'New York,']
['Plainview,', 'New', 'York,', 'United', 'States', 'New York,']
['Wolfeboro,', 'New', 'Hampshire,', 'United', 'States', 'New Hampshire,']
['Mule', 'Creek,', 'New', 'Mexico,', 'United', 'States', 'New Mexico,']
['New', 'York,', 'United', 'States', 'New York,']
['Charlotte,', 'North', 'Carolina,', 'United', 'States', 'North Carolina,']
['Germantown,', 'New', 'York,', 'United', 'States', 'New York,']
['Waxhaw,', 'North', 'Carolina', '28173,', 'United', 'States', 'North Carolina']
['Queens,', 'New', 'York', '11379,', 'United', 'States', 'New York']
['Charlotte,', 'North', 'Carolina,', 'United', 'States', 'North Carolina,']
['Portsmouth,', 'New', 'Hampshire,', 'United', 'States', 'New Hampshire,']
['3491', 'Pleasant', 'Grove', 'Church', 'Road,', 'Morrisville,', 'North', 'Carolina', '27560,', 'United', 'States', 'North Carolina']
['West', 'Columbia,', 'South', 'Carolina,', 'United', 'States', 'South Carolina,']
['26', 'Legion', 'Drive,', 'Smithtown,', 'New', 'York', '11787,', 'United', 'States', 'New York']
['Brooklyn,', 'New', 'York,', 'United', 'States', 'New York,']
['Cary,', 'North', 'Carolina,', 'United', 'States', 'North Carolina,']
['Portsmouth,', 'New', 'Hampshire', '03801,', 'United', 'States', 'New Hampshire']
['Bay', 'Shore,', 'New', 'York,', 'United', 'States', 'New York,']
['Littleton', 'New', 'Hampshire', 'New Hampshire']
['Mechanicville,', 'New', 'York,', 'United', 'States', 'New York,']
['Providence,', 'Rhode', 'Island,', 'United', 'States', 'Rhode Island,']
['Grafton,', 'North', 'Dakota,', 'United', 'States', 'North Dakota,']
['Queens,', 'New', 'York', '11694,', 'United', 'States', 'New York']
['New', 'York', 'City,', 'New', 'York,', 'United', 'States', 'New York']
['New', 'York', 'City,', 'New', 'York,', 'United', 'States', 'New York', 'New York']
['New', 'Jersey,', 'United', 'States', 'New Jersey,']
['Pomona,', 'New', 'York', 'New York']
['10', 'Via', 'Vecino,', 'Santa', 'Fe,', 'New', 'Mexico', '87506,', 'United', 'States', 'New Mexico']
['Roanoke', 'Rapids,', 'North', 'Carolina', '27870,', 'United', 'States', 'North Carolina']
['Binghamton,', 'New', 'York,', 'United', 'States', 'New York,']
['Santa', 'Fe,', 'New', 'Mexico,', 'United', 'States', 'New Mexico,']
['Hamilton', 'Township,', 'New', 'Jersey', '08619,', 'United', 'States', 'New Jersey']
['Portsmouth,', 'New', 'Hampshire', '03801,', 'United', 'States', 'New Hampshire']
['New', 'Jersey,', 'United', 'States', 'New Jersey,']

In [98]:
#len(western)

In [99]:
#clean_data_v3.head(60)

In [100]:
# make the dummies, actually

western_dict = {'West': 1, 'Midwest': 0, 'South': 0, 'Northeast': 0, 'International':0}
clean_data_v3['West'] = clean_data_v3['Location'].map(western_dict)

midwest_dict = {'West': 0, 'Midwest': 1, 'South': 0, 'Northeast': 0, 'International':0}
clean_data_v3['Midwest'] = clean_data_v3['Location'].map(midwest_dict)

south_dict = {'West': 0, 'Midwest': 0, 'South': 1, 'Northeast': 0, 'International':0}
clean_data_v3['South'] = clean_data_v3['Location'].map(south_dict)

northeast_dict = {'West': 0, 'Midwest': 0, 'South': 0, 'Northeast': 1, 'International':0}
clean_data_v3['Northeast'] = clean_data_v3['Location'].map(northeast_dict)

In [101]:
fuel_dict = {'Diesel': 1, 'Gasoline': 0, 'Bio-Diesel': 1, 'Other': 1}
clean_data_v3['Fuel Dummy'] = clean_data_v3['Fuel'].map(fuel_dict)

In [102]:
#clean_data_v3.to_csv('clean_data_v6.csv')

In [103]:
test_sum = clean_data_v3['Sink'][0] + clean_data_v3['Toilet'][0] + clean_data_v3['Water Heater'][0] + clean_data_v3['Shower'][0] + clean_data_v3['Fresh Water Tank (Built-in)'][0] + clean_data_v3['Fresh Water Tank (Portable)'][0]

In [104]:
test_sum

5

In [105]:
water_columns = ['Sink','Toilet','Water Heater','Shower','Fresh Water Tank (Built-in)','Fresh Water Tank (Portable)', 'Grey / Black Water Tanks']
test_total = clean_data_v3.loc[0,water_columns].sum()

In [106]:
test_total

6

In [110]:
#plumbing_score = []

for i in range(len(clean_data_v3['Sink'])):
    clean_data_v3['Plumbing Score'][i] = clean_data_v3.iloc[i, [21,23,30,32,34,35,36,55]].sum()
    #plumbing_score.append(score)

/tmp/ipykernel_283921/80507453.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data_v3['Plumbing Score'][i] = clean_data_v3.iloc[i, [21,23,30,32,34,35,36,55]].sum()

In [111]:
clean_data_v3['Plumbing Score'].head(15)

0     7
1     7
2     5
3     4
4     6
5     4
6     6
7     6
8     7
9     1
10    7
11    6
12    5
13    7
14    5
Name: Plumbing Score, dtype: int64

In [113]:
for i in range(len(clean_data_v3['Solar'])):
    clean_data_v3['Gadget Score'][i] = clean_data_v3.iloc[i, [16,17,18,19,20,22,25,31,33,39,40,41,44,46,47,50,51,54]].sum()

/tmp/ipykernel_283921/1655862259.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data_v3['Gadget Score'][i] = clean_data_v3.iloc[i, [16,17,18,19,20,22,25,31,33,39,40,41,44,46,47,50,51,54]].sum()

In [115]:
for i in range(len(clean_data_v3['Air Conditioner'])):
    clean_data_v3['Creature Comfort Score'][i] = clean_data_v3.iloc[i, [15,24,26,27,28,38,42,43,45,48,49,52,53]].sum()

/tmp/ipykernel_283921/2714073157.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data_v3['Creature Comfort Score'][i] = clean_data_v3.iloc[i, [15,24,26,27,28,38,42,43,45,48,49,52,53]].sum()

In [116]:
clean_data_v3.head()

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Wheelbase Binned,Size,West,Midwest,South,Northeast,Fuel Dummy,Plumbing Score,Gadget Score,Creature Comfort Score
0,2019 Silver 350 Transit DW HD High Roof Ecoboo...,84000.0,South,2019,Transit,28084.0,2WD,Clean,Automatic,Gasoline,...,Small,1,0,0,1,0,0,7,9,5
1,One of a Kind Ford Transit 350 AWD. Boat inspi...,190000.0,West,2021,Transit,3500.0,AWD,Clean,Automatic,Gasoline,...,Small,1,1,0,0,0,0,7,7,6
2,2021 Sprinter,99800.0,West,2021,Sprinter,3000.0,2WD,Clean,Automatic,Diesel,...,Small,1,1,0,0,0,1,5,11,5
3,2016 Sprinter 170,72000.0,West,2016,Sprinter,46000.0,2WD,Clean,Automatic,Diesel,...,Big,3,1,0,0,0,1,4,3,7
4,4x4 144 Mercedes sprinter,154000.0,West,2019,Sprinter,10000.0,4WD,Clean,Automatic,Diesel,...,Small,1,1,0,0,0,1,6,13,9

In [117]:
clean_data_v3.to_csv('clean_data_v6.csv')

In [118]:
clean_data_v3['Plumbing Score'].unique()

array([7, 5, 4, 6, 1, 2, 8, 0, 3])

In [119]:
clean_data_v3['Gadget Score'].unique()

array([ 9,  7, 11,  3, 13,  8,  6,  5, 12,  4,  1,  2, 10, 14, 15, 16,  0])

In [120]:
clean_data_v3['Creature Comfort Score'].unique()

array([ 5,  6,  7,  9,  3,  4,  1,  2,  8, 10,  0])

In [121]:
plumbing_bins = [-1,0,3,6,10]
labels = ['None','Basic','Standard','Deluxe']
clean_data_v3['Plumbing Amenities'] = pd.cut(clean_data_v3['Plumbing Score'], plumbing_bins, labels=labels)

plumbing_ordination = {"None":0, "Basic":1, "Standard":2, "Deluxe":3}
clean_data_v3["Plumbing"] = clean_data_v3["Plumbing Amenities"].replace(plumbing_ordination)

In [122]:
gadget_bins = [-1,0,5,10,15,20]
labels = ['None','Basic','Standard','Deluxe','Fully Loaded']
clean_data_v3['Gadget Amenities'] = pd.cut(clean_data_v3['Gadget Score'], gadget_bins, labels=labels)

gadget_ordination = {"None":0, "Basic":1, "Standard":2, "Deluxe":3, "Fully Loaded":4}
clean_data_v3["Gadgets"] = clean_data_v3["Gadget Amenities"].replace(gadget_ordination)

In [123]:
comfort_bins = [-1,0,3,7,11]
labels = ['None','Basic','Standard','Deluxe',]
clean_data_v3['Comfort Amenities'] = pd.cut(clean_data_v3['Creature Comfort Score'], comfort_bins, labels=labels)

comfort_ordination = {"None":0, "Basic":1, "Standard":2, "Deluxe":3}
clean_data_v3["Creature Comfort"] = clean_data_v3["Comfort Amenities"].replace(comfort_ordination)

In [124]:
clean_data_v3.head(15)

,Vehicle,Price,Location,Manufacturing Year,Make & Model,Mileage,Drive,Title Status,Transmission,Fuel,...,Fuel Dummy,Plumbing Score,Gadget Score,Creature Comfort Score,Plumbing Amenities,Plumbing,Gadget Amenities,Gadgets,Comfort Amenities,Creature Comfort
0,2019 Silver 350 Transit DW HD High Roof Ecoboo...,84000.0,South,2019,Transit,28084.0,2WD,Clean,Automatic,Gasoline,...,0,7,9,5,Deluxe,3,Standard,2,Standard,2
1,One of a Kind Ford Transit 350 AWD. Boat inspi...,190000.0,West,2021,Transit,3500.0,AWD,Clean,Automatic,Gasoline,...,0,7,7,6,Deluxe,3,Standard,2,Standard,2
2,2021 Sprinter,99800.0,West,2021,Sprinter,3000.0,2WD,Clean,Automatic,Diesel,...,1,5,11,5,Standard,2,Deluxe,3,Standard,2
3,2016 Sprinter 170,72000.0,West,2016,Sprinter,46000.0,2WD,Clean,Automatic,Diesel,...,1,4,3,7,Standard,2,Basic,1,Standard,2
4,4x4 144 Mercedes sprinter,154000.0,West,2019,Sprinter,10000.0,4WD,Clean,Automatic,Diesel,...,1,6,13,9,Standard,2,Deluxe,3,Deluxe,3
5,SKOOLIANA 5 WINDOW WHEEL CHAIR DOOR SHORT BUS,45000.0,West,2003,Other,162000.0,2WD,Clean,Automatic,Diesel,...,1,4,8,7,Standard,2,Standard,2,Standard,2
6,Adventure Camper Van has it all! - Ready to Tr...,45900.0,South,2016,Promaster,108500.0,2WD,Clean,Automatic,Gasoline,...,0,6,8,6,Standard,2,Standard,2,Standard,2
7,Fully Loaded Luxury Tiny Home on Wheels,144500.0,West,2021,Sprinter,119.0,2WD,Clean,Automatic,Diesel,...,1,6,8,5,Standard,2,Standard,2,Standard,2
8,Van Life Chicago 2021 Ram Promaster - 8020 Build,89500.0,Midwest,2021,Promaster,18200.0,2WD,Clean,Automatic,Gasoline,...,0,7,6,5,Deluxe,3,Standard,2,Standard,2
9,2017 Mercedes 2500 Sprinter 4x4 (Delivered New...,99500.0,West,2017,Sprinter,21000.0,4WD,Clean,Automatic,Diesel,...,1,1,13,7,Basic,1,Deluxe,3,Standard,2
10,NEW BUILD Ford Transit van conversion,69000.0,West,2018,Transit,65000.0,2WD,Clean,Automatic,Gasoline,...,0,7,6,6,Deluxe,3,Standard,2,Standard,2
11,**Price Drop! - Fully Converted 2020 Mercedes ...,173000.0,West,2020,Sprinter,4900.0,4WD,Clean,Automatic,Diesel,...,1,6,11,5,Standard,2,Deluxe,3,Standard,2
12,2016 Ram Promaster 2500 159WB Brand New Build,69900.0,Northeast,2016,Promaster,47000.0,2WD,Clean,Automatic,Gasoline,...,0,5,5,3,Standard,2,Basic,1,Basic,1
13,"New 2021 Transit 350 High Roof Extended, Seat ...",99000.0,West,2021,Transit,600.0,2WD,Clean,Automatic,Gasoline,...,0,7,7,7,Deluxe,3,Standard,2,Standard,2
14,2020 Ford Transit AWD 4 Seater,129900.0,Midwest,2020,Transit,1300.0,AWD,Clean,Automatic,Gasoline,...,0,5,12,9,Standard,2,Deluxe,3,Deluxe,3

In [125]:
#clean_data_v3.to_csv('clean_data_v7.csv')

In [128]:
drivetrain_dict = {'2WD':0, 'AWD':1, '4WD':2, 'Other':0}

clean_data_v3['Drivetrain'] = clean_data_v3['Drive'].map(drivetrain_dict)

In [129]:
clean_data_v3.to_csv('clean_data_v7.csv')